apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: busybox:latest
        command: ["sh","-c", "sleep 10 && echo Pre-sync job completed"]
      restartPolicy: Never
  backoffLimit: 2